#!/bin/bash
#
# tomcat	Startup script for the Apache Tomcat
#
# chkconfig: 345 80 15
# description: Apache Tomcat is an open source software implementation of the Java Servlet and JavaServer Pages technologies.

# Source function library.
. /etc/rc.d/init.d/functions

prog='tomcat'
user='tomcat'

exec='$CATALINA_HOME/bin/catalina.sh'
pidfile='/var/run/tomcat/catalina.pid'
RETVAL=0

start() {
	su - $user -c "$exec start"
	RETVAL=$?
	if [ $RETVAL -ne 0 ]; then
		action $"Starting $prog: " /bin/false
	else
		action $"Starting $prog: " /bin/true
	fi
}

stop() {
	su - $user -c "$exec stop"
	RETVAL=$?
	if [ $RETVAL -ne 0 ]; then
		action $"Stopping $prog: " /bin/false
	else
		action $"Stopping $prog: " /bin/true
		rm -f $pidfile
	fi
}

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status -p ${pidfile} $prog
		exec
		;;
	restart)
		stop
		start
		;;
	configtest|version)
		$exec $@
		RETVAL=$?
		;;
	*)
		echo $"Usage: $prog {start|stop|status|restart|configtest|version}"
		exit 2
esac

exit $RETVAL